config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :contentkeywords
  resources :contents
  resources :homes
  resources :infos
  resources :projects
  resources :users
  resources :works
  resources :abouts
  resources :myhelps
  resources :sliderkeywords
  resources :sliders
  resources :sucais

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boxcontent.rb
class Boxcontent < ApplicationRecord
  belongs_to :boxkeyword
end

app/models/boxkeyword.rb
class Boxkeyword < ApplicationRecord
  has_many :boxcontents
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :contentkeyword
  has_attached_file :contentimg, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :contentimg
end

app/models/contentkeyword.rb
class Contentkeyword < ApplicationRecord
  has_many :contents
end

app/models/slider.rb
class Slider < ApplicationRecord
  belongs_to :sliderkeyword
end

app/models/sliderkeyword.rb
class Sliderkeyword < ApplicationRecord
  has_many :sliders
end

app/models/sucai.rb
class Sucai < ApplicationRecord
  has_attached_file :sucaiimg, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :sucaiimg
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

  before_action :set_content, only: [:show, :edit, :update, :destroy]
  def index
    @contents = Content.all
  end

  def edit
    @content = Content.find(params[:id])
    @contentkeywords = Contentkeyword.all
  end

  def new
    @content = Content.new
    @contentkeywords = Contentkeyword.all
  end

  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to contents_path, notice: 'Dgt was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to contents_path, notice: 'user was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_path, notice: '删除成功' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_content
    @content = Content.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def content_params
    params.require(:content).permit(:title,:content, :summary,:contentkeyword_id,:contentimg)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
    sliderkeyword = Sliderkeyword.find_by_keyword('home')
    @sliders = sliderkeyword.sliders
  end

end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  def index
    contentkeyword = Contentkeyword.find_by_keyword('install')
    @installs = contentkeyword.contents
    contentkeyword = Contentkeyword.find_by_keyword('enterprice')
    @enterprices = contentkeyword.contents
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/myhelps_helper.rb
module MyhelpsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/sucais_helper.rb
module SucaisHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/contents/_form.html.erb
<script>

    $(document).ready(function(){

     $('#contentkeywordselect').change(function(){

         $('#contentkeywordid').val($('#contentkeywordselect').val());
     });


  });

    function proreadURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#contentimg').attr('src', e.target.result);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }
</script>
<div class="col-md-12 ibox ibox-content">
  <div class="ibox-content form-horizontal m-t">
    <div class="form-group">
      <%= form_for(@content,:html => {:class=>'form-horizontal m-t',:multipart => true}) do |f| %>

          <div class="form-group">
            <label class="col-sm-3 control-label">标题：</label>
            <div class="col-sm-8">
              <%= f.text_field :title,class:"form-control" %>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-3 control-label">内容区域：</label>
            <div class="col-sm-8">
              <%= f.hidden_field :contentkeyword_id,class:"form-control",id:'contentkeywordid' %>
              <select class="form-control" id="contentkeywordselect">
                <option value="0">请选择内容区域</option>
                <% @contentkeywords.each do |contentkeyword| %>
                    <option value=<%=contentkeyword.id %>><%=contentkeyword.name %></option>
                    <% end %>
              </select>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-3 control-label">简介：</label>
            <div class="col-sm-8">
              <%= f.text_area :summary,class:"form-control" %>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label">列表图片：</label>
            <div class="col-sm-8">
              <%= f.file_field :contentimg,class:"form-control",:onchange => "proreadURL(this)" %>
              <img id="contentimg" width="600px"  src=<%= @content.contentimg.url %> >
            </div>

          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label">内容：</label>
            <div class="col-sm-8">
              <%= f.kindeditor :content,class:"form-control" %>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-3 control-label"></label>
            <div class="col-sm-8 text-right">
              <%= f.submit '确定',class: "btn btn-primary"%>&nbsp;<%= link_to "返回",contents_path,class: "btn btn-primary " %>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/contents/edit.html.erb
<div class="container bs-docs-container">
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">编辑网站内容</div>
    <div class="panel-body">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/contents/index.html.erb
<div class="container bs-docs-container">
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">网站内容</div>
    <div class="panel-body">

    </div>

    <!-- Table -->
    <table class="table">
        <th class="text-center">名称</th>
      <th class="text-center">分类</th>
      <th class="text-center">创建日期</th>
      <th class="text-center">操作</th>
      <%@contents.each do |content| %>
          <tr>
            <td>
              <%= content.title %>
            </td>
            <td>
              <%= content.contentkeyword.name %>
            </td>
            <td>
              <%= content.created_at.strftime('%Y-%m-%d %H:%M:%S') %>
            </td>
            <td>
              <%= link_to '编辑',edit_content_path(content) %>
              <%= link_to '删除',content, method: :delete, data: { confirm: '确认删除?' } %>
            </td>
          </tr>
      <% end %>
    </table>

  </div>
  <div class="text-right">
    <%= link_to "新增",new_content_path,class: "btn btn-primary" %>
  </div>
</div>

app/views/contents/new.html.erb
<div class="container bs-docs-container">
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">新增网站内容</div>
    <div class="panel-body">
      <%= render 'form' %>
    </div>




  </div>
</div>

app/views/contents/show.html.erb
<%= render 'layerbegin' %>

<div class="container" style="margin-top: 120px;">
  <div class="text-center">
    <span>
     <b> <%= @content.title %></b>
    </span>
    <span class="pull-right text-muted">
      <%=@content.created_at.strftime('%Y-%m-%d %H:%M:%S')  %>
    </span>
  </div>
  <hr>
  <br>
  <div>
    <%= @content.content.html_safe %>
  </div>
</div>