config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :contentkeywords
  resources :contents
  resources :homes
  resources :infos
  resources :projects
  resources :users
  resources :works
  resources :abouts
  resources :myhelps
  resources :sliderkeywords
  resources :sliders
  resources :sucais

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boxcontent.rb
class Boxcontent < ApplicationRecord
  belongs_to :boxkeyword
end

app/models/boxkeyword.rb
class Boxkeyword < ApplicationRecord
  has_many :boxcontents
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :contentkeyword
  has_attached_file :contentimg, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :contentimg
end

app/models/contentkeyword.rb
class Contentkeyword < ApplicationRecord
  has_many :contents
end

app/models/slider.rb
class Slider < ApplicationRecord
  belongs_to :sliderkeyword
end

app/models/sliderkeyword.rb
class Sliderkeyword < ApplicationRecord
  has_many :sliders
end

app/models/sucai.rb
class Sucai < ApplicationRecord
  has_attached_file :sucaiimg, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :sucaiimg
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
    sliderkeyword = Sliderkeyword.find_by_keyword('home')
    @sliders = sliderkeyword.sliders
  end

end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  def index
    contentkeyword = Contentkeyword.find_by_keyword('install')
    @installs = contentkeyword.contents
    contentkeyword = Contentkeyword.find_by_keyword('enterprice')
    @enterprices = contentkeyword.contents
  end
end

app/controllers/sliderkeywords_controller.rb
class SliderkeywordsController < ApplicationController

  before_action :set_sliderkeyword, only: [:show, :edit, :update, :destroy]
  def index
    @sliderkeywords = Sliderkeyword.all
  end

  def edit
    @sliderkeyword = Sliderkeyword.find(params[:id])
  end

  def new
    @sliderkeyword = Sliderkeyword.new
  end

  def create
    @sliderkeyword = Sliderkeyword.new(sliderkeyword_params)

    respond_to do |format|
      if @sliderkeyword.save
        format.html { redirect_to sliderkeywords_path, notice: 'Dgt was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @sliderkeyword.update(sliderkeyword_params)
        format.html { redirect_to sliderkeywords_path, notice: 'user was successfully updated.' }
        format.json { render :show, status: :ok, location: @sliderkeyword }
      else
        format.html { render :edit }
        format.json { render json: @sliderkeyword.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @sliderkeyword.destroy
    respond_to do |format|
      format.html { redirect_to sliderkeywords_path, notice: '删除成功' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_sliderkeyword
    @sliderkeyword = Sliderkeyword.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def sliderkeyword_params
    params.require(:sliderkeyword).permit(:keyword , :name)
  end

end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/myhelps_helper.rb
module MyhelpsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sliderkeywords_helper.rb
module SliderkeywordsHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/sucais_helper.rb
module SucaisHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/sliderkeywords/_form.html.erb
<div class="col-md-12 ibox ibox-content">
  <div class="ibox-content form-horizontal m-t">
    <div class="form-group">
      <%= form_for(@sliderkeyword,:html => {:class=>'form-horizontal m-t',:multipart => true}) do |f| %>

          <div class="form-group">
            <label class="col-sm-3 control-label">关键字：</label>
            <div class="col-sm-5">
              <%= f.text_field :keyword,class:"form-control" %>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-3 control-label">名称：</label>
            <div class="col-sm-5">
              <%= f.text_field :name,class:"form-control" %>
            </div>
          </div>


          <div class="form-group">
            <label class="col-sm-3 control-label"></label>
            <div class="col-sm-5 text-right">
              <%= f.submit '确定',class: "btn btn-primary"%>&nbsp;<%= link_to "返回",sliderkeywords_path,class: "btn btn-primary " %>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/sliderkeywords/edit.html.erb
<div class="container bs-docs-container">
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">编辑滚动关键字</div>
    <div class="panel-body">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/sliderkeywords/index.html.erb
<div class="container bs-docs-container">
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">滚动关键字</div>
    <div class="panel-body">

    </div>

    <!-- Table -->
    <table class="table">
      <th class="text-center">
        关键字
      </th>
      <th class="text-center">名称</th>
      <th class="text-center">操作</th>
      <%@sliderkeywords.each do |sliderkeyword| %>
          <tr>
            <td>
              <%= sliderkeyword.name %>
            </td>

            <td>
              <%= sliderkeyword.keyword %>
            </td>
            <td>
              <%= link_to '编辑',edit_sliderkeyword_path(sliderkeyword) %>
              <%= link_to '删除',sliderkeyword, method: :delete, data: { confirm: '确认删除?' } %>
            </td>
          </tr>
      <% end %>
    </table>

  </div>
  <div class="text-right">
    <%= link_to "新增",new_sliderkeyword_path,class: "btn btn-primary" %>
  </div>
</div>

app/views/sliderkeywords/new.html.erb
<div class="container bs-docs-container">
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">新增滚动关键字</div>
    <div class="panel-body">
      <%= render 'form' %>
    </div>




  </div>
</div>