config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :contentkeywords
  resources :contents
  resources :homes
  resources :infos
  resources :projects
  resources :users
  resources :works
  resources :abouts
  resources :myhelps
  resources :sliderkeywords
  resources :sliders
  resources :sucais

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boxcontent.rb
class Boxcontent < ApplicationRecord
  belongs_to :boxkeyword
end

app/models/boxkeyword.rb
class Boxkeyword < ApplicationRecord
  has_many :boxcontents
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :contentkeyword
  has_attached_file :contentimg, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :contentimg
end

app/models/contentkeyword.rb
class Contentkeyword < ApplicationRecord
  has_many :contents
end

app/models/slider.rb
class Slider < ApplicationRecord
  belongs_to :sliderkeyword
end

app/models/sliderkeyword.rb
class Sliderkeyword < ApplicationRecord
  has_many :sliders
end

app/models/sucai.rb
class Sucai < ApplicationRecord
  has_attached_file :sucaiimg, :url => "/:attachment/:id/:basename.:extension",  :path => ":rails_root/public/:attachment/:id/:basename.:extension"
  do_not_validate_attachment_file_type :sucaiimg
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
    sliderkeyword = Sliderkeyword.find_by_keyword('home')
    @sliders = sliderkeyword.sliders
  end

end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  def index
    contentkeyword = Contentkeyword.find_by_keyword('install')
    @installs = contentkeyword.contents
    contentkeyword = Contentkeyword.find_by_keyword('enterprice')
    @enterprices = contentkeyword.contents
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/myhelps_helper.rb
module MyhelpsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sliders_helper.rb
module SlidersHelper
end

app/helpers/sucais_helper.rb
module SucaisHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/application/_layerbegin.html.erb
<style>
    .cd-vertical-nav li:first-of-type a::after {
        /* change icon using image sprites */
        /*background-position: 0px -48px;*/
        content: "\f015";
        color: black;
        font-size: 16px;
        top: 4px;
        font-family: FontAwesome;
        /* fix bug with transitions - set scale(0.01) rather than scale(0) */
        -webkit-transform: translateX(-50%) translateY(4.5em) scale(0.01);
        -moz-transform: translateX(-50%) translateY(4.5em) scale(0.01);
        -ms-transform: translateX(-50%) translateY(4.5em) scale(0.01);
        -o-transform: translateX(-50%) translateY(4.5em) scale(0.01);
        transform: translateX(-50%) translateY(4.5em) scale(0.01);
    }

    .cd-vertical-nav li:nth-of-type(2) a::after {
        /*background-position: 0px -32px;*/
        content: "\f0f7";
        color: black;
        font-size: 16px;
        top: 4px;
        font-family: FontAwesome;
        -webkit-transform: translateX(-50%) translateY(1.5em) scale(0.01);
        -moz-transform: translateX(-50%) translateY(1.5em) scale(0.01);
        -ms-transform: translateX(-50%) translateY(1.5em) scale(0.01);
        -o-transform: translateX(-50%) translateY(1.5em) scale(0.01);
        transform: translateX(-50%) translateY(1.5em) scale(0.01);
    }

    .cd-vertical-nav li:nth-of-type(3) a::after {
        /*background-position: 0px -16px;*/
        content: "\f091";
        color: black;
        font-size: 16px;
        top: 4px;
        font-family: FontAwesome;
        -webkit-transform: translateX(-50%) translateY(-1.5em) scale(0.01);
        -moz-transform: translateX(-50%) translateY(-1.5em) scale(0.01);
        -ms-transform: translateX(-50%) translateY(-1.5em) scale(0.01);
        -o-transform: translateX(-50%) translateY(-1.5em) scale(0.01);
        transform: translateX(-50%) translateY(-1.5em) scale(0.01);
    }

    .cd-vertical-nav li:nth-of-type(4) a::after {
        /*background-position: 0px 0px;*/
        content: "\f201";
        color: black;
        font-size: 16px;
        top: 4px;
        font-family: FontAwesome;
        -webkit-transform: translateX(-50%) translateY(-4.5em) scale(0.01);
        -moz-transform: translateX(-50%) translateY(-4.5em) scale(0.01);
        -ms-transform: translateX(-50%) translateY(-4.5em) scale(0.01);
        -o-transform: translateX(-50%) translateY(-4.5em) scale(0.01);
        transform: translateX(-50%) translateY(-4.5em) scale(0.01);
    }

    .cd-vertical-nav li:nth-of-type(5) a::after {
        /*background-position: 0px 0px;*/
        content: "\f0c0";
        color: black;
        font-size: 16px;
        top: 4px;
        font-family: FontAwesome;
        -webkit-transform: translateX(-50%) translateY(-7.5em) scale(0.01);
        -moz-transform: translateX(-50%) translateY(-7.5em) scale(0.01);
        -ms-transform: translateX(-50%) translateY(-7.5em) scale(0.01);
        -o-transform: translateX(-50%) translateY(-7.5em) scale(0.01);
        transform: translateX(-50%) translateY(-7.5em) scale(0.01);
    }

</style>

<div class="navbar navbar-fixed-top" role="navigation"
     data-0="line-height:100px; height:100px; background-color:rgba(0,0,0,0.3);"
     data-300="line-height:60px; height:60px; background-color:rgba(0,0,0,1);">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="fa fa-bars color-white"></span>
      </button>
      <h1><a  href="index.html" data-0="line-height:90px;" data-300="line-height:50px;" style="font-size: 30px;color:#ffffff"><img src="/sucaiimgs/10/liushushulogo.png" alt="萝卜特甜" style="height: 60px;width: inherit;">&nbsp;&nbsp;&nbsp;刘叔叔</a>
      </h1>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav" data-0="margin-top:20px;" data-300="margin-top:5px;">
        <% if request.url.include?('homes') %>
        <li class="active"><a class="smooth" href=<%= homes_path %>>首页</a></li>
            <% else %>
            <li><a class="smooth" href=<%= homes_path %>>首页</a></li>
            <% end %>
        <% if request.url.include?('infos') %>
            <li class="active"><a class="smooth" href=<%= infos_path %>>最新资讯</a></li>
            <% else %>
            <li><a class="smooth" href=<%= infos_path %>>最新资讯</a></li>
            <% end %>
        <% if request.url.include?('projects') %>
            <li class="active"><a class="smooth" href=<%= projects_path %>>工程案例</a></li>
            <% else %>
            <li><a class="smooth" href=<%= projects_path %>>工程案例</a></li>
            <% end %>
        <% if request.url.include?('users') %>
            <li class="active"><a class="smooth" href=<%= users_path %>>用户中心</a></li>
            <% else %>
            <li><a class="smooth" href=<%= users_path %>>用户中心</a></li>
            <% end %>
        <% if request.url.include?('works') %>
            <li class="active"><a class="smooth" href=<%= works_path %>>师傅中心</a></li>
            <% else %>
            <li><a class="smooth" href=<%= works_path %>>师傅中心</a></li>
            <% end %>
        <% if request.url.include?('myhelps') %>
            <li class="active"><a class="smooth" href=<%= myhelps_path %>>帮助中心</a></li>
            <% else %>
            <li><a class="smooth" href=<%= myhelps_path %>>帮助中心</a></li>
            <% end %>
        <% if request.url.include?('abouts') %>
            <li class="active"><a class="smooth" href=<%= abouts_path %>>关于我们</a></li>
            <% else %>
            <li><a class="smooth" href=<%= abouts_path %>>关于我们</a></li>
            <% end %>
      </ul>
    </div>
    <!--/.navbar-collapse -->
  </div>
</div>

app/views/application/_layerend.html.erb
<footer id="footer" class="footer" style="background: #222222;">
  <div class="container" style="color: #a0a0a0;margin-top: 50px;background: #222222;">
    <div class="col-md-6">
      <p>&nbsp;</p>
      <p>
        &copy;&nbsp;2017 昆明复永科技有限公司
      </p>
      <p>
        <i class="fa fa-building-o"></i>&nbsp;&nbsp;云南省昆明市呈贡区仕林街云上云大数据8幢8207室
      </p>
      </p>
      <i class="fa fa-phone"></i>&nbsp;86-871-63513368
      <p>
    </div>
    <div class="col-md-6 text-right" style="padding: 10px;">
      <img width="20%" src="image/wxqrcode.png">
    </div>
  </div>
</footer>